---
blank_issues_enabled: true
contact_links:
  - name: Discuss a feature
    url: 'https://github.com/bareos/bareos-testing/discussions/new?category=feature'
    about: |
      Start a discussion about a new feature Bareos should have
  - name: Ask a Question
    url: 'https://groups.google.com/u/1/g/bareos-users'
    about: |
      Ask a question about how to use Bareos using google groupe discussions
