name: "[Release] python-bareos -> https://pypi.org/"

on:
  push:
    tags:
      - Release/*

jobs:
  build-and-publish:
    name: "Build python-bareos and publish it to https://pypi.org/"
    runs-on: ubuntu-18.04

    steps:
    - name: "Checkout source"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: "Checkout tags"
      # for get-version.sh, an unshallow git checkout with tags is needed.
      run:  git fetch --tag

    - name: "Set up Python"
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: "Build python package"
      run: |
        pip install --user wheel
        cd python-bareos
        # sdist mangles around with version information.
        # We replace ~pre with dev, as this will not be modified.
        # (pre will be replaced with rc).
        ../docs/manuals/source/get-version.sh > bareos/VERSION.txt
        printf "Version: %s\n" $(cat bareos/VERSION.txt)
        python setup.py sdist bdist_wheel

    - name: "Create artifact"
      # creating an artifact is not required for publishing to pypi.
      uses: actions/upload-artifact@v2
      with:
        path: python-bareos/dist/

    - name: "Publish to pypi.org"
      uses: pypa/gh-action-pypi-publish@v1.1.0
      with:
        password: ${{ secrets.pypi_password }}
        packages_dir: python-bareos/dist/
